version: "3.8"

services:
  backend:
    image: docker.io/library/python:3.11-slim
    container_name: "${PROJECT_NAME:-stackforge}_backend"
    working_dir: /app
    volumes:
      - ./backend:/app:Z
    ports:
      - "8000:8000"
    command: sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped

  frontend:
    image: docker.io/library/node:20-slim
    container_name: "${PROJECT_NAME:-stackforge}_frontend"
    working_dir: /src
    volumes:
      - ./frontend:/src:Z
    ports:
      - "5173:5173"
    command: sh -c "npm install --no-audit --no-fund && npm run dev -- --host 0.0.0.0 --port 5173"
    restart: unless-stopped

  postgres:
    image: docker.io/library/postgres:15
    container_name: "${PROJECT_NAME:-stackforge}_postgres"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-mydb}"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    restart: unless-stopped
    profiles:
      - postgres

  mysql:
    image: docker.io/library/mysql:8
    container_name: "${PROJECT_NAME:-stackforge}_mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-rootpass}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-mydb}"
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
    volumes:
      - mysql_data:/var/lib/mysql:Z
    ports:
      - "3306:3306"
    restart: unless-stopped
    profiles:
      - mysql

volumes:
  postgres_data: {}
  mysql_data: {}
