version: "3.8"

services:
  backend:
    image: docker.io/library/node:20-slim
    container_name: "${PROJECT_NAME:-express-vue}_backend"
    working_dir: /
    volumes:
      - ./backend/app:/app:Z
    ports:
      - "5000:5000"
    command: sh -c "rm -rf node_modules package-lock.json && npm cache clean --force && npm install --no-audit --no-fund && npm start"
    restart: unless-stopped
    env_file:
      - ./backend/.env

  frontend:
    image: docker.io/library/node:20-slim
    container_name: "${PROJECT_NAME:-express-vue}_frontend"
    working_dir: /src
    volumes:
      - ./frontend:/src:Z
    ports:
      - "5173:5173"
    command: sh -c "rm -rf node_modules package-lock.json && npm cache clean --force && npm install --no-audit --no-fund && npm run dev -- --host 0.0.0.0 --port 5173"
    restart: unless-stopped
    depends_on:
      - backend

  postgres:
    image: docker.io/library/postgres:15
    container_name: "${PROJECT_NAME:-express-vue}_postgres"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-mydb}"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    restart: unless-stopped
    profiles:
      - postgres

  mysql:
    image: docker.io/library/mysql:8
    container_name: "${PROJECT_NAME:-express-vue}_mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-rootpass}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-mydb}"
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
    volumes:
      - mysql_data:/var/lib/mysql:Z
    ports:
      - "3306:3306"
    restart: unless-stopped
    profiles:
      - mysql

  mongo:
    image: docker.io/library/mongo:7
    container_name: "${PROJECT_NAME:-express-vue}_mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:-user}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-password}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE:-mydb}"
    volumes:
      - mongo_data:/data/db:Z
    ports:
      - "27017:27017"
    restart: unless-stopped
    profiles:
      - mongo

volumes:
  postgres_data: {}
  mysql_data: {}
  mongo_data: {}
