import React from "react";

export default function App() {
	return (
		<div style={{ padding: 24 }}>
			<h1>Hello from React + Vite</h1>
			<p>This is a minimal frontend generated by stackforge-cli.</p>
		</div>
	);
}
